### ISSUE TITLE
Spec should specify a short permission lifetime

### ISSUE THREAD

**Issue by pes10k** [w3c/mediacapture-screen-share#134]
Currently the spec describes a permission for allowing the site to access the screen.  However, its not clear what the lifetime of this permission is.  Given the sensitivity of the information, it would be good to specify a short lifetime for this capability.

**Comment by jyasskin** [comment]
https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia includes 

> The User Agent MUST NOT create a permission storage entry with a value of "granted".

which I believe means that every call to `getDisplayMedia()` will prompt (or auto-deny). Since the result object from `getDisplayMedia()` can't outlive the tab, that caps the lifetime of the capability. It probably wouldn't be a good idea to additionally specify a wall-time limit on how long someone can share their screen.

**Comment by pes10k** [comment]
Gotcha, as long as that boils down to "document lifetime" then it addresses my concern.  If thats the case, i'll close this issue

**Comment by alvestrand** [comment]
That was the intention, I believe: No permanent access to screenshare, permission dies with the document.

**Comment by pes10k** [comment]
thanks for clarifying @alvestrand and @jyasskin, closing
