### ISSUE TITLE
Capture-current-tab: Managing capture-ability by cross-origin embedder as opt-in vs. opt-out

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-screen-share#156]
An API for capturing the current tab, to be named getCurrentBrowsingContextMedia (or getTabMedia, or something similar), is [under discussion](https://github.com/w3c/mediacapture-screen-share/pull/148). Concerns have been expressed over how this could be used to circumvent the origin-isolation model, as well as harvest user data. Both @jan-ivar and I have made suggestions for ways to address the former of these two concerns. The most important difference between these two suggestion, IMHO, is whether the capture-ability of embedded resources by their embedder is opt-in or opt-out. ([Opt-in suggestion](https://github.com/w3c/mediacapture-screen-share/issues/155), [opt-out suggestion](https://docs.google.com/presentation/d/1CeNeno5XuDhm1mpnVyE9eT14YKZgZUtgQsJfC8uqEpA/edit#slide=id.gaef31c926d_1_52).) I suggest that we leave other threads to discuss the particulars of their respective proposals, and use this discussion thread to try and arrive at a decision over whether opt-in or opt-out is more appropriate.

In a discussion with a potential user of the proposed API, they have expressed that it would be prohibitively difficult for them to transition their very substantial application, which embeds plenty of cross-origin first- and third-party resources, into an opt-in model, and maintain it over time. The cost (and risks) are simply too great, they tell me. They would simply not use the new API if it's opt-in.

It might be that an opt-in model would be superior from a theoretical security perspective. I am concerned that these gains would remain theoretical due to lack of adoption. It seems to me that the real choice is not between opt-in and opt-out. Rather, IMHO, the choice is between opt-out and no-feature, leaving native applications as the only way to support the intended use case .

I think it would be good if we could hear from other prospective users of this API. I will do my best to invite some, and I encourage everybody else to do the same.

**Comment by jan-ivar** [comment]
(At the risk of paraphrasing the minutes which aren't up yet) the WG at [last interim](https://www.w3.org/2011/04/webrtc/wiki/December_14_2020) seemed to disfavor opt-out over security concerns with site-driven capture, wishing instead to explore forms of opt-in, e.g. by blanking out non-consenting iframes.

> ... it would be prohibitively difficult for them to transition their very substantial application

Conversely, it would be prohibitively difficult for the rest of the web to opt-out of this new feature and its risks.

> ... lack of adoption

Does this potential user foresee embedding rich media features in the future? If so, they'll want powerful features like `SharedArrayBuffer` anyway, which [is already opt-in](https://web.dev/why-coop-coep/).

> I think it would be good if we could hear from other prospective users of this API.

Yes, clarification of use cases would be good, as so far they seem to only involve sites that want to be captured. `getDisplayMedia` remains the catch-all for those that don't, but it seems safer to leave those in the hands of the user.

**Comment by youennf** [comment]
As @jan-ivar mentioned, the interim meeting mentioned the possibility to either capture parts of the page, or to capture the whole page but with parts of the page being sanitized. It would be good if use cases were precise enough to understand whether these possibilities are worth investigating.

It was also noted that getDisplayMedia is the backup plan in case the new API is not powerful enough. It would be worth exploring how much of the use cases could be fulfilled by an improved getDisplayMedia prompt, based on some heuristics (user history, user opt-in, user logged-in...).

@eladalon1983, do you know how your usecase is positioned for both things?

**Comment by jan-ivar** [comment]
@eladalon1983 Since we ran out of time in the meeting I'm adding some feedback here. I'm going to ignore that we disagree on the security properties of the proposed API for a moment, to see if we can make progress on cropping orthogonally to it:

> From [slides](https://docs.google.com/presentation/d/1crumgYj4eHkjo04faLktPTg0QoYJhTFoosEBudfJBuw/edit#slide=id.g7954c29f8a_2_14)
> <img src="https://user-images.githubusercontent.com/3136226/105072152-84b26000-5a53-11eb-89dc-b2805846624a.png" width="250">

If I understand correctly, a top-level page from site A is capturing its tab and wants to crop the output to only include a sub-region _inside_ a sub-iframe containing a participating site B, Is that right? And cropping needs to be robust and frame-accurate enough to not accidentally share even a split-frame more, to avoid revealing sensitive info like speaker notes?

If so, then this seems problematic on a couple of levels. For one, the iframe may be in a separate process, which might slip up on a frame here and there. And inherently having the party that decides what area should be cropped separate from the source being cropped seems like a dependency that would be hard to manage e.g. requiring different teams to coordinate (no pun intended).

If we don't use explicit coordinates (which I could easily see going out of sync), relying on some agreed-upon `<div>` would also mean adding code to fish out said div from the iframe, and things can go wrong there a well (site B updating the `'id`). Also, site A would not see the `<div>` in site B's page unless they were same orgin.

A safer approach seems to be to arrange for the participating page on site B to be doing the capture itself. It controls its own layout, and can specify a crop region using its own `<div>` easily. Permissions policy would still ensure that the end user perceives the request as coming from site A, so that shouldn't be a problem.

**Comment by eladalon1983** [comment]
Thank you for the lightning-fast follow-up, @jan-ivar. I have opened [another thread](https://github.com/w3c/mediacapture-screen-share/issues/158) to discuss this topic. I'd like to continue the cropping discussion there, and keep the current thread focused on opt-in vs. opt-out - a topic I still hope to revive after syncing with some internal stakeholders. 😃 I'll quote your message and respond to it in that other thread.

**Comment by jan-ivar** [comment]
> use this discussion thread to try and arrive at a decision over whether opt-in or opt-out is more appropriate.

@eladalon1983 Based on your https://github.com/w3c/mediacapture-screen-share/issues/155#issuecomment-801493527, can we close this?

**Comment by eladalon1983** [comment]
Yes, by all means.
