### ISSUE TITLE
Address nullability of DisplayMediaStreamOptions.controller

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-screen-share#236]
I believe we should make the new `CaptureController controller` member in the `DisplayMediaStreamOptions`  dictionary either:
- optional with `CaptureController? controller = null;`- even though it is already optional according to https://webidl.spec.whatwg.org/#dictionary-member-optional, 
- or remove the `= null;` part that was added in https://github.com/w3c/mediacapture-screen-share/pull/235/commits/73770e40390ebc25fbad80a5a7171da53d487afc

https://github.com/w3c/mediacapture-screen-share/blob/7857efe4c25628af2e25fca5eda9ab93927c9bd3/index.html#L913

**Comment by beaufortfrancois** [comment]
Note that https://github.com/whatwg/webidl/pull/1205 would go towards removing the null part and simply have `CaptureController controller;`.

**Comment by eladalon1983** [comment]
The [first revision](https://github.com/w3c/mediacapture-screen-share/pull/235/commits/fbd5ebcbf2062c1228e9ff10ec360668b79021a4) indeed had it as `CaptureController controller;`.
During the editors' meeting, it was requested that `= null` be added.
I'm fine either way.

**Comment by beaufortfrancois** [comment]
What are the arguments for making this nullable, when this member is already optional?

**Comment by eladalon1983** [comment]
@jan-ivar, I think you wanted this change? Or do I misremember?

**Comment by youennf** [comment]
> What are the arguments for making this nullable, when this member is already optional?

Agreed, we should remove ` = null` from the IDL definition.

**Comment by beaufortfrancois** [comment]
FYI, @annevk approved recently https://github.com/whatwg/webidl/pull/1205/ which makes sure the WebIDL spec [dictionary example](https://webidl.spec.whatwg.org/#example-f7efabfd) does not have members that are both optional and nullable. The reason being it's better to explicitly handle the case where optional members are omitted.



<img width="782" alt="image" src="https://user-images.githubusercontent.com/634478/193293663-828331ea-b140-44f0-b154-975d14ebcc0f.png">

**Comment by jan-ivar** [comment]
> optional with CaptureController? controller = null;- even though it is already optional according to https://webidl.spec.whatwg.org/#dictionary-member-optional,

You are correct we need `?` here, thanks for catching this! I've written https://github.com/w3c/mediacapture-screen-share/pull/238 to take care of this.

Note that `?` makes it _[nullable](https://webidl.spec.whatwg.org/#idl-nullable-type)_, which it has to be to have a default value of `null`, not optional, which you are correct to observe that dictionary members already are when they aren't qualified with the [required](https://webidl.spec.whatwg.org/#required-dictionary-member) keyword.

> Note that https://github.com/whatwg/webidl/pull/1205 would go towards removing the null part and simply have `CaptureController controller;`.

That PR [removed](https://github.com/whatwg/webidl/pull/1205/files) nullable from DOMString members, which I approve of, because nullable strings have poor characteristics (they introduce type-duality since `typeof null` is `"object"` not `"string"`). `null` also has terrible conversion properties to string in JS (`"" + undefined` produces `"undefined"`).

But I disagree with the OP in that PR that members need to be required to be nullable. I see no support for such a position from first principles, nor do I interpret the fact that it went unchallenged in review since the PR itself was fine.

> What are the arguments for making this nullable, when this member is already optional?

The argument is that `null` is the natural default value for this argument in the [getDisplayMedia](https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia) algorithm where it is used as input, [as argued by you](https://github.com/w3c/mediacapture-screen-share/pull/235#discussion_r983553441) (I agree with you on this, since this is likely to be written in c++).

AFAIK there is no web developer observable difference here, so this should suffice as an argument I think?

**Comment by youennf** [comment]
This might be observable if passing null would reject getDisplayMedia promise in one case and not the other.

Why allowing to pass a null value and an undefined value to controller field?
Are there existing APIs doing so?

It seems unnecessary and increases a bit UA generated code.

**Comment by annevk** [comment]
You generally shouldn't need nullable dictionary members to indicate missing values. Optional, i.e., undefined, is the right way to go about that. For new APIs we don't want undefined and null  to mean the same thing. That typically results in null throwing, just like any other unsupported type would.

Null can be reasonable if there's a getter somewhere that returns null and it's logical to pass the value of that getter into the API taking the dictionary member.

**Comment by eladalon1983** [comment]
Making it a non-nullable optional seems like the most straight-forward way to ensure JS code is unambiguous and predictable. Apps either fail to supply a value, or they supply a patently legal value (modulo reusing an old controller). Developers don't need multiple ways of expressing the same thing.

**Comment by jan-ivar** [comment]
I'm trying to back up my statements, but its making me fall behind in the conversation, so apologies for taking a bit to address all the claims being made here. I would encourage others to back up opinions with supporting documents as well.

> it's better to explicitly handle the case where optional members are omitted.

This seems to go against [6.5. Make method arguments optional if possible](https://w3ctag.github.io/design-principles/#optional-parameters) which says defaults are good: _"If an argument for an API method has a reasonable default value, make that argument optional and specify the default value."_

Default values prevent an implementation from telling the difference between whether a member is present with the default value or absent. This seems a desirable invariant for all algorithms except those that overload these differences with additional semantics, and such subtlety generally seems like a bad idea to me, and is not the case here.

> This might be observable if passing null would reject getDisplayMedia promise in one case and not the other.

> Why allowing to pass a null value and an undefined value to controller field?

> Are there existing APIs doing so?

I believe the [Nullable conversion steps](https://webidl.spec.whatwg.org/#es-nullable-type) allow `undefined` to be coerced to `null`: _"Otherwise, if V is null or undefined, then return the IDL [nullable type](https://webidl.spec.whatwg.org/#dfn-nullable-type) T? value null."_ So I believe all APIs that take nullable types do this. ~Again, I see not web developer impact here, but please prove me wrong, as I cannot prove a negative.~

[Edit:] I stand corrected that there is in fact web developer observable difference. @youennf  is right that one option would reject on `null` (and I failed to even consider it as I assumed wrongly everyone found this to be an undesirable trait).

**Comment by beaufortfrancois** [comment]
I've played a bit in a Chromium build to see how it reacts to those API shapes and here are my results when I pass `{controller: null}`:

1. With `CaptureController controller`, I get a TypeError. See below

<img width="889" alt="Screen Shot 2022-09-30 at 17 41 30" src="https://user-images.githubusercontent.com/634478/193307144-6b3f066b-814e-4379-a473-4512f8e1e50e.png">

2. With `CaptureController? controller = null`, there's no JS error.

**Comment by jan-ivar** [comment]
> For new APIs we don't want undefined and null to mean the same thing.

That's interesting. Can you please link to support for this advice? I couldn't find it in the design guidelines.

> That typically results in null throwing, just like any other unsupported type would.

Even for object and interface inputs? E.g. we want the following to reject?
```js
let controller = null;

button.onclick = async () =>  {
  await navigator.mediaDevices.getDisplayMedia({controller}); // TypeError ?
}
```
I'm no fan of `null` personally, but I wasn't aware we'd gotten there yet.

**Comment by annevk** [comment]
I'm not sure if there's a good link for this, but that's how JavaScript does this. Note that there is a default here, it's not just stated explicitly: undefined. https://github.com/whatwg/webidl/issues/905 will make this better, but that will take some time.

https://w3ctag.github.io/design-principles/#optional-parameters might be a good place to put this. Want to PR that too @mgiuca? 😊

**Comment by jan-ivar** [comment]
Since I can't find this advice anywhere, could someone find me a link to a precedent here that isn't a legacy API? (I looked through all of HTML for one and couldn't find it).

Also, how do TypeScript folks operate? Do they expect `null` to be valid input to methods taking optional interfaces?

**Comment by annevk** [comment]
https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions for instance. Handled here https://dom.spec.whatwg.org/#event-flatten-more (note that internally not given is represented as null, but null cannot be passed on the JS side).

**Comment by jan-ivar** [comment]
> ... but that's how JavaScript does this.

Default function arguments in JS [seem to work that way, while `??` works another](https://jsfiddle.net/jib1/zoxepamv/), treating `null` and `undefined` the same. But those aren't examples of throwing or rejecting. Where does JS throw or reject on `null`?

If we reject on `null`, then the subset of web developers who operate in larger code bases that use `null` liberally might end up writing defensive code now in order to separate concerns:
```js
async function foo(controller) {
  await navigator.mediaDevices.getDisplayMedia({controller: controller ?? undefined});
}
```
This seem sub-optimal. While a controller of `false` or `0` is a type mismatch, `null` isn't in JS (`typeof new CaptureController()` and `typeof null` are both `"object"`).

What's the specific advantage of treating `controller: null` as an error here instead of "no controller"?

Also, when is `null` to be used?

> https://w3ctag.github.io/design-principles/#optional-parameters

This concerns method arguments. Does this mean we're also moving toward:
```js
platformObj.foo("hi", undefined, 3); // accepted
platformObj.foo("hi", null, 3); // TypeError ?
```

**Comment by jan-ivar** [comment]
> https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions for instance. Handled here https://dom.spec.whatwg.org/#event-flatten-more (note that internally not given is represented as null, but null cannot be passed on the JS side).

Thanks for those links. That does seem to set a precedent. I still have my questions/doubts above though.

The link also illustrates a common expectation to use `null` in implementation code. But I agree this is a separate concern: A benefit of defaults in my mind is to simplify prose (and implementations) by capitalizing on the invariants they provide so we don't need to write so many `if`s in prose. In the AddEventListenerOptions case, had `undefined` been used internally, I suppose the prose could be simplified to
```
Let passive be options["passive"].
Let signal be options["signal"].
```
? That seems to gel with https://github.com/whatwg/webidl/issues/905.

**Comment by annevk** [comment]
I think currently you cannot use the simplified prose as Web IDL normalizes undefined to missing. It would probably work if we get rid of optional/missing entirely.

**Comment by jan-ivar** [comment]
Maybe we could add a WebIDL extended attribute that turned missing into `null`?

**Comment by jan-ivar** [comment]
To understand the general advice here better, is it meant to also apply to dictionary arguments to constructors?

I notice in both this and the AddEventListenerOptions example, there were no corresponding `readonly` attribute exposing the internal slot for JS to read back what was set, if anything (is the advice for such an attribute to still yield `null`, or `undefined`)? Interfaces don't support missing AFAIK). If the answer is the readonly attribute should be `null`, then not accepting `null` as input would seem mildly unexpected perhaps, and also break any (encouraged or discouraged?) constructor duplicator patterns popularized by Events., and used in places like RTCSessionDescription E.g.
```js
const a = new Foo({bar: new Bar()})
const b = new Foo({});
const c = b.bar; // null or undefined?
const d = new Foo(b); // b is member equivalent and has toJSON(), but TypeError over b.bar being null?
```

**Comment by youennf** [comment]
An example of where it makes some sense to use an optional nullable dictionary member is RequestInit.body (https://fetch.spec.whatwg.org/#requestinit). Request has a nullable body getter (https://fetch.spec.whatwg.org/#dom-body-body) and it might be handy to use this getter when creating a new Request from an existing one.

In our particular case, there is no corresponding controller getter so keeping it as a simple optional member seems good.

**Comment by eladalon1983** [comment]
Does this need to go to a formal vote in the WG, or can we converge on a decision in GitHub? The opinions I believe I am reading are:
* @eladalon1983: Either decision is OK, but preference for `CaptureController controller;`.
* @beaufortfrancois: Preference for `CaptureController controller;`.
* @youennf: Preference for `CaptureController controller;`.
  * "keeping it as a simple optional member seems good."
* @annevk: Preference for `CaptureController controller;`.
  * "You generally shouldn't need nullable dictionary members to indicate missing values."
* @jan-ivar: Preference for `CaptureController controller = null;`.

If I am reading everyone correctly, it's Jan-Ivar on one side and the rest on another. Jan-Ivar, do you believe this is an important issue, or can we go with the popular vote in this case?

**Comment by jan-ivar** [comment]
Folks seem to be landing on the idea that `null` shouldn't be valid input _unless_ a nullable getter exists somewhere for the thing we may wish to pass in. It's true we can always make it nullable later if we ever end up defining such a getter, except...

A flaw in this logic seems to be it assumes we are in control of all getters, or that only platform getters matter.

JS-library getters would either need to adopt the (novel?) pattern of returning `undefined`, or callers would need to use
```js
async function foo(bar) {
  await navigator.mediaDevices.getDisplayMedia({{controller: bar.controller && undefined});
}
```

**Comment by jan-ivar** [comment]
But in the interest of progress, I see no immediate problem with removing nullable that we cannot undo later.

**Comment by eladalon1983** [comment]
> But in the interest of progress, I see no immediate problem with removing nullable that we cannot undo later.

Great. Would you please re-review #237 in light of that?
