### ISSUE TITLE
Fullscreen needs handling (was: Powerpoint is special)

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#29]
We will have to detect when a particular Powerpoint window has become full screen and shift the window share to the presentation.  We might want to extend the same sort of privilege to other applications that shift to a full screen mode.

**Comment by aboba** [comment]
Not clear this is needed if the user can select the monitor that the presentation is displayed on.

**Comment by mhofman** [comment]
It is needed if the user is able to select application / window, and that application / window transitions to a full screen rendering.

We are getting a ton of complaints from users that start sharing "Powerpoint" because we allow selecting windows as a source, and subsequently start presentation mode and attendees only see a black screen.

If only full screens are allowed to be selected as a source, this is not an issue, but since this API does not allow the website to constraint which source the user can select to work around the issue, the user agent should be smart enough to respect the user's choice of "sharing the powerpoint window".

**Comment by ShijunS** [comment]
> the user agent should be smart enough to respect the user's choice of "sharing the powerpoint window".

Yes, it'd make sense to leave it as a UA implementation decision in order to deliver a seamless user experience.  As an example, for a specific app, e.g. PowerPoint, the UA can always chose to stream content out of a "primary" display surface of the app during runtime.  The UA can dynamically decide which display surface is the "primary" one during runtime, in case there are multiple to select from.

**Comment by mhofman** [comment]
I think the idea is to specify or at least document this behavior to avoid un-optimal implementations like we currently have?

**Comment by ShijunS** [comment]
Yes, a non-normative implementation suggestion would help.

**Comment by dot-slash-s** [comment]
Update from Feb 21st meeting 
Write a proposal based on the following lines
"""
Applications that go full-screen might need special treatment
Modes for consideration:
    “application” DisplayCaptureSurfaceType selected
    “window” DisplayCaptureSurfaceType selected
In either case, if the UA is able to make unambiguous 1:1 determination that the invisible window displayed in full screen mode maps to the window (initially selected) from the same application, Screen Capture should be allowed.
Proposal: Write informal note to explain the above and consequences of mapping failure.
"""

**Comment by henbos** [comment]
Fullscreen is a platform-specific concept, we decided at TPAC to have informative language but nothing normative. "Fullscreen" is not a special mode.

**Comment by eladalon1983** [comment]
This issue has not seen any activity in a long time. It appears that, important though it is, it is not important enough to merit action. I am closing this. Feel free to reopen.
