### ISSUE TITLE
Spec should make use of https://w3c.github.io/mediacapture-main/#dfn-create-a-mediastreamtrack to create MediaStreamTrack

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#293]
This would make sure that source is registered on the document that created it.

**Comment by alvestrand** [comment]
I assume that "mediaDevicesToTieSourceTo" is null here. So the operation is calling "MediaStreamTrack source-specific constructions steps", which is null unless otherwise specified. Do they need specification?

The call(s)  to "create a mediastreamtrack" would be part of what happens in "Prompt the user to choose", which retuns "options", but the caller in createDisplayMedia() assumes that what's returned is either tracks or "denied".

**Comment by youennf** [comment]
> I assume that "mediaDevicesToTieSourceTo" is null here

No, it would be the `mediaDevices` object used when calling `mediaDevices.getDisplayMedia`.

**Comment by youennf** [comment]
Following on today's editor meeting, the way MediaStreamTrack transfer is defined was discussed in 2021 and ended up in a successful CfC on 09/30/2021.
That led to the current addition to media capture-extensions, which is clear about the lifetime of capture tracks, in particular:
```
When originalContext goes away, trackSource gets ended, thus transferredTrack gets ended.
```

We can of course revisit this once we have more use cases (for instance we are also discussing in parallel whether to restrict transfer to same agent cluster).
In the meantime, I think this issue and the related PR are just editorial.

@eladalon1983, wdyt?
