### ISSUE TITLE
Browser tab sharing

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c/mediacapture-screen-share#51]
Add `tab` display surface for sharing single browser tab.

**Comment by bgschiller** [comment]
I found my way here by way of [this stack overflow post](https://stackoverflow.com/questions/47022259/firefox-specify-current-window-to-stream-with-getusermedia). I believe it would also be useful to be able to specify streaming the *current* tab.

**Comment by FluorescentHallucinogen** [comment]
BTW, Chrome already has tab sharing implemented via `mandatory: {chromeMediaSource: 'tab'}` constraint, but:
1. `mandatory` is old constraint syntax
2. `chromeMediaSource` is non-standard, Chrome-only thing
3. it works only in Chrome extensions

![chrome-tab-sharing](https://user-images.githubusercontent.com/7892779/32454287-db5ceb64-c32f-11e7-812f-72deb4e124a3.png)

**Comment by FluorescentHallucinogen** [comment]
@martinthomson @dontcallmedom @vivienlacourba @keithgrif PTAL.

**Comment by dot-slash-s** [comment]
Adding the proposal from virtual interim here to discuss more. [This was not discussed during feb interim due to time limits]
"""
Define a new DisplayCaptureSurfaceType: “active-window”
“active-window” is the current active display area (say the current browser tab) that triggered the getDisplayMedia()
List “active-window” information in the UX selection list for sharing.
This had advantage of avoiding the need to list all the tabs otherwise and bad UX.
"""

**Comment by martinthomson** [comment]
This could be a UX question: if browsers treat their own tabs as windows, and properly mark the current tab, then this doesn't require anything special.

**Comment by aboba** [comment]
Consensus from the April VI [was for option 2.](https://www.w3.org/2018/04/12-webrtc-minutes) which requires no change to the specification.  See slides here: 
https://docs.google.com/presentation/d/1sboQqMc5O1-oZ7w0ZY1VUyhY8JG0VxOzU8kAQitoHJU/edit#slide=id.g32a9278ac5_0_6
