### ISSUE TITLE
Offer high level source filtering

### ISSUE THREAD

**Issue by niklasenbom** [w3c/mediacapture-screen-share#62]
Current implementations in Chrome and Firefox both offer the ability for the web app to restrict the sharing choice to desktop, window, tabs etc. Web apps like Google Hangouts use this functionality and would like to keep it. There's also technical reasons to why this makes sense, for example tab sharing is much cheaper on system resources, and unlike desktop and window sharing audio capture always work. By restricting the choice to tab sharing a web app could know that you can do high fps streaming with audio.

**Comment by jan-ivar** [comment]
The sharing of a browser surface come with unique [security risks](https://tools.ietf.org/html/draft-ietf-rtcweb-security-10#section-4.1.1), which is why the spec expressly forbids influencing selection toward these.

The [decision](https://www.w3.org/2018/09/25-webrtc-minutes.html) at [yesterday's meeting](https://docs.google.com/presentation/d/1uZUmLe62faePYC2HMI_x_ltDjn_peJG71yk_PZn4hzc/edit?ts=5ba53026#slide=id.g411fb2292a_0_38) was "Don't add this. Go back to github and ask for more compelling use cases."

@niklasenbom are there compelling use-cases?

**Comment by niklasenbom** [comment]
2 main reasons: 

1. We have a lot of data showing that users today are heavily skewed (> 90%) towards sharing the full desktop, which is the worst option when it comes to security and privacy. By promoting window and tab sharing already at the web UI level in Google Meet we have been able to influence the users to share more restricted surfaces. Doing this at the web UI level makes it possible to make the options content specific, for example a Google doc would be offered as sharing a tab only, an app as window only, and desktop sharing would only be a last resort.

2. Tab sharing offers possibilities not available with other surface type. It's cheap to get high frame rate capture, audio is always available, and you can get content clues to optimize encoding. By knowing you'll get a tab as MediaStream content we can offer functionality not possible to implement with other surface types (e.g. share a youtube page with high fps and audio).

**Comment by jan-ivar** [comment]
>  sharing the full desktop, which is the worst option when it comes to security and privacy.

TBC the worst option from a security and privacy threat perspective is the sharing of a web surface. The reasons for this are [non-obvious](https://blog.mozilla.org/webrtc/share-browser-windows-entire-screen-sites-trust/). Full desktop is bad because it often reveals a web surface.

**Comment by henbos** [comment]
Why does the UI have to reside inside of the web app to best influence the user to make the best choice? A good UI should help the user make the best choice, why is that UI inside the web app and not inside the browser's picker? The problems you're describing are not specific to a particular web app (any screen sharing web app would have the same pros/cons of a source); they are, however, largely specific to a _browser implementation_.

Should your web app limit or encourage users to tab capture because Chrome does high fps screen share in that case, even though that distinction is irrelevant in Firefox? (I'm not saying this is necessarily the case, I'm making up an example.)

My position is that it is up to the browser/implementation to help the user make the best choice, not the web app, unless the limitations are universal to any browser. You might end up filtering out an option that some other browser implementation is able to handle.

With regards to audio I think audio source capabilities are platform specific and the web app should have little say in what audio the user picks, just like the web app has no say in which screen or which window the user picks. Audio being complementary part of screen sharing, we're making it optional to satisfy "audio:true" unlike "video:true". As long as the picker is clear to the user what they are sharing we should be good?

**Comment by henbos** [comment]
@niklasenbom, @uysalere

**Comment by alvestrand** [comment]
Decision: This should be left to browser UI.
