### ISSUE TITLE
Clarify that we only process/TypeError on applicable constraints 

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#95]
Spec says: *"For each member present in constraints whose value, value, is a dictionary, run the following steps:"*

This is too broad a pre-processing of constraints, and goes against https://github.com/w3c/mediacapture-main/pull/542.

It's also hard to implement, as WebIDL bindings typically map dictionaries to `struct` in c++, with no obvious way to enumerate dictionary members—nor should we do this, as it's a design problem that MediaTrackConstraintSet cuts across spec domains like this.

For example, screen sharing has no audio constraints (because audio constraints are *microphone* constraints). Terminology baggage.

I'll add a PR to clarify that we only throw on "applicable" constraints, which are the [ones explicitly listed in the screen share spec](https://w3c.github.io/mediacapture-screen-share/#constrainable-properties).

**Comment by alvestrand** [comment]
There's existing language (recently added) to say "ignore non-applicable constraints" in the selectSettings algorithm. Can what you are looking for be accomodated by broadening that language?
Though I'm worried that we may declare something that throws on {volume: {exact: 'wrong'}} (because it understands that exact volumes take numbers, not strings) non-compliant; I think that in Chrome we do the typechecking/conversion pass before we do the "is this constraint applicable" pass - which your suggestion would render non-conformant.

**Comment by jan-ivar** [comment]
Sorry i wasn't clear here. I was referring to pre-validation steps we do on all constraints in `getDisplauMedia()`. I'll provide a PR. Easier to look at that than explain.
